import {StyleSheet} from 'react-native';


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    backgroundColor: '#e7f5ff',
    padding: 8,
    marginLeft: 8,
    borderRadius: 8,
  },
  headerGradient: {
    paddingBottom: 20,
  },
  headerContainer: {
    paddingTop: 16,
    paddingHorizontal: 20,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1c7ed6',
  },
  card: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
    shadowColor: '#1971c2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#e7f5ff',
  },
  headerSubtitle: {
    fontSize: 16,
    color: '#4dabf7',
    marginTop: 4,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 80,
    marginTop: 16,
  },
  sectionContainer: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1971c2',
    marginLeft: 8,
  },
  addButton: {
    backgroundColor: '#339af0',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  addButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    marginLeft: 6,
  },
  medicationCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#1971c2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e7f5ff',
  },
  medicationTime: {
    backgroundColor: '#e7f5ff',
    padding: 12,
    borderRadius: 12,
    marginRight: 16,
    alignItems: 'center',
    minWidth: 80,
  },
  medicationTimeOverdue: {
    backgroundColor: '#fff5f5',
    borderWidth: 1,
    borderColor: '#ffc9c9',
  },
  timeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1971c2',
    marginTop: 4,
    textAlign: 'center',
    maxWidth: 80,
  },
  timeTextOverdue: {
    color: '#fa5252',
  },
  medicationDetails: {
    flex: 1,
  },
  medicationName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1971c2',
  },
  medicationDosage: {
    fontSize: 14,
    color: '#74c0fc',
    marginTop: 4,
  },
  repeatPatternText: {
    color: '#228be6',
    fontSize: 13,
    marginTop: 4,
  },
  notesText: {
    color: '#adb5bd',
    fontSize: 13,
    marginTop: 4,
  },
  checkButton: {
    backgroundColor: '#339af0',
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1971c2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  emptyState: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    shadowColor: '#1971c2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e7f5ff',
  },
  emptyStateText: {
    fontSize: 16,
    color: '#1971c2',
    fontWeight: '500',
    marginTop: 12,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#74c0fc',
    marginTop: 4,
  },
  historyCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#1971c2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e7f5ff',
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  historyTypeContainer: {
    flex: 1,
  },
  historyTypeBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  historyTypeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  historyDate: {
    fontSize: 12,
    color: '#74c0fc',
    fontWeight: '500',
  },
  deleteButton: {
    padding: 8,
    color: '#339af0',
    backgroundColor: '#e7f5ff',
    borderRadius: 8,
  },
  historyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1971c2',
    marginBottom: 8,
  },
  historyDescription: {
    fontSize: 14,
    color: '#495057',
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(25, 113, 194, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1971c2',
  },
  input: {
    backgroundColor: '#e7f5ff',
    padding: 14,
    borderRadius: 12,
    marginBottom: 16,
    fontSize: 16,
    color: '#1971c2',
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  inputLabel: {
    fontSize: 14,
    color: '#74c0fc',
    marginBottom: 6,
    fontWeight: '500',
  },
  typeSelector: {
    marginBottom: 16,
  },
  typeGrid: {
    flexDirection: 'row',
    paddingVertical: 8,
  },
  typeOption: {
    backgroundColor: '#e7f5ff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 10,
  },
  typeOptionSelected: {
    backgroundColor: '#339af0',
  },
  typeOptionText: {
    fontSize: 14,
    color: '#1971c2',
    fontWeight: '500',
  },
  typeOptionTextSelected: {
    color: '#ffffff',
  },
  dateTimeButton: {
    backgroundColor: '#e7f5ff',
    padding: 14,
    borderRadius: 12,
    marginBottom: 16,
  },
  dateTimeWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateTimeText: {
    marginLeft: 12,
    fontSize: 16,
    color: '#1971c2',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  cancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e7f5ff',
  },
  cancelButtonText: {
    color: '#74c0fc',
    fontWeight: '600',
    fontSize: 16,
  },
  saveButton: {
    backgroundColor: '#339af0',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 12,
    shadowColor: '#1971c2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  saveButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
  medicineCard: {
    padding: 0,
    overflow: 'hidden',
  },
  medicineGradient: {
    borderRadius: 16,
  },
  medicineContent: {
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  medicineTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 8,
  },
  medicineDescription: {
    fontSize: 14,
    color: '#e7f5ff',
    maxWidth: '90%',
  },
  medicineIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Styles for repeat pattern selection
  repeatPatternContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    justifyContent: 'space-between',
  },
  repeatPatternOption: {
    backgroundColor: '#e7f5ff',
    paddingVertical: 10,
    paddingHorizontal: 0,
    marginBottom: 8,
    borderRadius: 12,
    width: '48%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d0ebff',
  },
  repeatPatternSelected: {
    backgroundColor: '#339af0',
    borderColor: '#228be6',
  },
  repeatPatternText: {
    fontSize: 14,
    color: '#1971c2',
    fontWeight: '500',
  },
  repeatPatternTextSelected: {
    color: '#ffffff',
  },
  headerTitleWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    marginRight: 10,
  },
  modalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalIcon: {
    marginRight: 8,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e7f5ff',
    borderRadius: 12,
    marginBottom: 16,
  },
  inputIcon: {
    marginLeft: 12,
    marginRight: 8,
  },
  repeatPatternRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  notesRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 4,
  },
  notesText: {
    color: '#adb5bd',
    fontSize: 13,
    marginLeft: 4,
    flex: 1,
  },
  historyDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  historyDate: {
    fontSize: 12,
    color: '#74c0fc',
    fontWeight: '500',
    marginLeft: 4,
  },
  descriptionContainer: {
    flexDirection: 'row',
    marginTop: 8,
  },
  descriptionIcon: {
    marginRight: 6,
    marginTop: 2,
  },
  historyTypeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  historyTypeBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  typeOption: {
    backgroundColor: '#e7f5ff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
});

export default styles;